# Generated by Django 4.1 on 2022-11-13 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_bloguser_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BLogUSer',
            new_name='ImagenUser',
        ),
    ]
