# Generated by Django 4.1 on 2022-11-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_imagenuser_img_imagenuser_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenuser',
            old_name='Img',
            new_name='img',
        ),
    ]
