# Generated by Django 4.1 on 2022-11-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_img_imagenuser_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenUser',
        ),
    ]
