# Generated by Django 4.1 on 2022-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_postblog_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='descriction',
            field=models.TextField(verbose_name='Descripsion'),
        ),
    ]
