# Generated by Django 4.1 on 2022-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_postblog_descriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='tipo',
            field=models.CharField(choices=[('news', 'news'), ('technology', 'technology'), ('video game', 'video game')], max_length=50),
        ),
    ]
