# Generated by Django 4.1 on 2022-11-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_user_perfiles_user_rename_user_postblog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.perfiles'),
        ),
    ]
