# Generated by Django 4.1 on 2022-11-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_postblog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiles',
            old_name='img',
            new_name='imagen',
        ),
    ]
