# Generated by Django 4.1 on 2022-11-16 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_postblog_perfil_alter_postblog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='postblog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
