# Generated by Django 4.1.3 on 2022-11-16 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_postblog_perfil_alter_postblog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='img',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='img', verbose_name='Imagen'),
        ),
    ]
