# Generated by Django 4.1.3 on 2022-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_postblog_data_alter_postblog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
