# Generated by Django 4.1.3 on 2022-11-16 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_alter_perfiles_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='perfiles',
            new_name='profile',
        ),
    ]
