# Generated by Django 4.1.3 on 2022-11-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_perfiles_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagen',
            new_name='image',
        ),
    ]
