# Generated by Django 4.1 on 2022-11-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_rename_imagen_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='tipo',
            field=models.CharField(choices=[('NOticias', 'Noticias'), ('Juegos', 'Juegos'), ('Tecnología', 'Tecnología')], max_length=50),
        ),
    ]
