# Generated by Django 4.1 on 2022-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_postblog_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='complete',
            field=models.BooleanField(default=True, verbose_name='completado'),
        ),
    ]
