# Generated by Django 4.1 on 2022-11-18 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_postblog_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='data',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 18, 16, 51, 29, 870850, tzinfo=datetime.timezone.utc)),
        ),
    ]
