# Generated by Django 4.1 on 2022-11-18 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_postblog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 18, 16, 55, 44, 478090, tzinfo=datetime.timezone.utc)),
        ),
    ]
