# Generated by Django 4.1 on 2022-11-18 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_postblog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
