# Generated by Django 4.1 on 2022-11-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_postblog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cometarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postblog')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile')),
            ],
        ),
    ]
