# Generated by Django 4.1.3 on 2022-11-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0034_remove_cometarios_perfil_cometarios_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cometarios',
            options={'ordering': ['data']},
        ),
        migrations.RemoveField(
            model_name='cometarios',
            name='Post',
        ),
        migrations.AddField(
            model_name='cometarios',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cometarios',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
