# Generated by Django 4.1.3 on 2022-11-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_remove_cometarios_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cometarios',
            old_name='post',
            new_name='title',
        ),
    ]
