# Generated by Django 4.1.3 on 2022-11-19 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0039_remove_cometarios_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cometarios',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comentario', to=settings.AUTH_USER_MODEL),
        ),
    ]
