# Generated by Django 4.1.3 on 2022-11-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_cometarios_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cometarios',
            old_name='user',
            new_name='author',
        ),
    ]
