# Generated by Django 4.1.3 on 2022-11-19 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0043_alter_cometarios_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cometarios',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Comentario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
