# Generated by Django 4.1.3 on 2022-11-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_cometarios_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cometarios',
            options={},
        ),
    ]
