# Generated by Django 4.1.3 on 2022-11-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_alter_cometarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postblog',
            options={},
        ),
    ]
