# Generated by Django 4.1.3 on 2022-11-22 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0048_alter_cometarios_options_alter_postblog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
