# Generated by Django 4.1.3 on 2022-11-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_alter_postblog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cometarios',
            old_name='author',
            new_name='aser',
        ),
    ]
