# Generated by Django 4.1.3 on 2022-11-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_rename_author_cometarios_aser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cometarios',
            old_name='aser',
            new_name='user',
        ),
    ]
